export const SCALES = {
  "CARS": {
    name: "CARS",
    questions: [
      { id: "cars_1", label: "1. Relating to People" },
      { id: "cars_2", label: "2. Imitation" },
      { id: "cars_3", label: "3. Emotional Response" },
      { id: "cars_4", label: "4. Body Use" },
      { id: "cars_5", label: "5. Object Use" },
      { id: "cars_6", label: "6. Adaptation to Change" },
      { id: "cars_7", label: "7. Visual Response" },
      { id: "cars_8", label: "8. Listening Response" },
      { id: "cars_9", label: "9. Taste, Smell, and Touch Response and Use" },
      { id: "cars_10", label: "10. Fear or Nervousness" },
      { id: "cars_11", label: "11. Verbal Communication" },
      { id: "cars_12", label: "12. Nonverbal Communication" },
      { id: "cars_13", label: "13. Activity Level" },
      { id: "cars_14", label: "14. Level and Consistency of Intellectual Response" },
      { id: "cars_15", label: "15. General Impressions" }
    ]
  },
  "GARS-2": {
    name: "GARS-2",
    questions: [
      { id: "gars_1", label: "1. Avoids establishing eye contact, looks away when eye contact is made." },
      { id: "gars_2", label: "2. Stares at hands, objects, or items in the environment for at least 5 seconds." },
      { id: "gars_3", label: "3. Flicks fingers rapidly in front of eyes for periods of 5 seconds or more." },
      { id: "gars_4", label: "4. Eats specific foods and refuses to eat what most people usually will eat." },
      { id: "gars_5", label: "5. Licks, tastes, or attempts to eat inedible objects." },
      { id: "gars_6", label: "6. Smells or sniffs objects (e.g. toys, person's hands)." },
      { id: "gars_7", label: "7. Whirls, turns in circles." },
      { id: "gars_8", label: "8. Spins objects not meant for spinning." },
      { id: "gars_9", label: "9. Rocks back and forth while seated or standing." },
      { id: "gars_10", label: "10. Makes rapid lunging, darting movements." },
      { id: "gars_11", label: "11. Prances (i.e., walks on tip toes)." },
      { id: "gars_12", label: "12. Flaps hands or fingers in front of the face or at sides." },
      { id: "gars_13", label: "13. Makes high-pitched sounds or other vocalizations for self-stimulation." },
      { id: "gars_14", label: "14. Slaps, hits, or bites self or attempts to injure self." },
      { id: "gars_15", label: "15. Repeats (echoes) words verbally or with signs." },
      { id: "gars_16", label: "16. Repeats words out of context (words heard more than 1 min earlier)." },
      { id: "gars_17", label: "17. Repeats words or phrases over and over." },
      { id: "gars_18", label: "18. Speaks or signs with flat tone, affect, or dysrhythmic patterns." },
      { id: "gars_19", label: "19. Responds inappropriately to simple commands." },
      { id: "gars_20", label: "20. Looks away or avoids looking at speaker when name is called." },
      { id: "gars_21", label: "21. Does not ask for things he or she wants." },
      { id: "gars_22", label: "22. Does not initiate conversations with peers or adults." },
      { id: "gars_23", label: "23. Uses 'yes' and 'no' inappropriately." },
      { id: "gars_24", label: "24. Uses pronouns inappropriately (refers to self as 'he' or 'you')." },
      { id: "gars_25", label: "25. Uses the word 'I' inappropriately." },
      { id: "gars_26", label: "26. Repeats unintelligible sounds (babbles) over and over." },
      { id: "gars_27", label: "27. Uses gestures instead of speech or signs to obtain objects." },
      { id: "gars_28", label: "28. Inappropriately answers questions about a statement or brief story." },
      { id: "gars_29", label: "29. Avoids eye contact, looks away when someone looks at him or her." },
      { id: "gars_30", label: "30. Stares or looks unhappy or unexcited when praised or entertained." },
      { id: "gars_31", label: "31. Resists physical contact from others (e.g., hugs, pats)." },
      { id: "gars_32", label: "32. Does not imitate other people when imitation is required." },
      { id: "gars_33", label: "33. Withdraws, remains aloof, or acts standoffish in group situations." },
      { id: "gars_34", label: "34. Behaves in an unreasonably fearful, frightened manner." },
      { id: "gars_35", label: "35. Is unaffectionate; does not give affectionate responses." },
      { id: "gars_36", label: "36. Shows no recognition that a person is present (looks through people)." },
      { id: "gars_37", label: "37. Laughs, giggles, cries inappropriately." },
      { id: "gars_38", label: "38. Uses toys or objects inappropriately." },
      { id: "gars_39", label: "39. Does certain things repetitively, ritualistically." },
      { id: "gars_40", label: "40. Becomes upset when routines are changed." },
      { id: "gars_41", label: "41. Responds negatively or with temper tantrums to commands/requests." }
    ]
  },
  "M-CHAT-R": {
    name: "M-CHAT-R",
    questions: [
      { id: "mchat_1", label: "1. If you point at something across the room, does your child look at it?" },
      { id: "mchat_2", label: "2. Have you ever wondered if your child might be deaf?" },
      { id: "mchat_3", label: "3. Does your child play pretend or make-believe?" },
      { id: "mchat_4", label: "4. Does your child like climbing on things?" },
      { id: "mchat_5", label: "5. Does your child make unusual finger movements near his or her eyes?" },
      { id: "mchat_6", label: "6. Does your child point with one finger to ask for something or to get help?" },
      { id: "mchat_7", label: "7. Does your child point with one finger to show you something interesting?" },
      { id: "mchat_8", label: "8. Is your child interested in other children?" },
      { id: "mchat_9", label: "9. Does your child show you things by bringing them to you... just to share?" },
      { id: "mchat_10", label: "10. Does your child respond when you call his or her name?" },
      { id: "mchat_11", label: "11. When you smile at your child, does he or she smile back at you?" },
      { id: "mchat_12", label: "12. Does your child get upset by everyday noises?" },
      { id: "mchat_13", label: "13. Does your child walk?" },
      { id: "mchat_14", label: "14. Does your child look you in the eye when you are talking/playing?" },
      { id: "mchat_15", label: "15. Does your child try to copy what you do?" },
      { id: "mchat_16", label: "16. If you turn your head to look at something, does your child look around to see what you are looking at?" },
      { id: "mchat_17", label: "17. Does your child try to get you to watch him or her?" },
      { id: "mchat_18", label: "18. Does your child understand when you tell him or her to do something?" },
      { id: "mchat_19", label: "19. If something new happens, does your child look at your face to see how you feel?" },
      { id: "mchat_20", label: "20. Does your child like movement activities (e.g., being swung or bounced)?" }
    ]
  }
};
